name: Frontend CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Install xvfb and dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install xvfb

      - name: Start xvfb
        if: runner.os == 'Linux'
        run: |
          export DISPLAY=:99
          Xvfb $DISPLAY -screen 0 1920x1080x24 -ac &

      - name: Run tests
        if: runner.os == 'Linux'
        run: |
          xvfb-run --auto-servernum npm test
          pkill -f "Xvfb"

      - name: Run tests
        if: runner.os != 'Linux'
        run: npm test

      - name: Build
        run: npm run build

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: frontend-build
          path: dist/

