name: Frontend CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Install xvfb and dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libxi6 libgconf-2-4

      - name: Start Xvfb
        if: runner.os == 'Linux'
        run: |
          export DISPLAY=:99
          Xvfb $DISPLAY -screen 0 1920x1080x24 > /dev/null 2>&1 &

      - name: Run tests
        run: |
          DISPLAY=:99 npm test
          TEST_EXIT_CODE=$?
          exit $TEST_EXIT_CODE

      - name: Stop Xvfb
        if: runner.os == 'Linux'
        run: |
          pkill -f "Xvfb"

      - name: Build
        run: npm run build

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: frontend-build
          path: dist/

